LLM_config:
  Agent:
    API_backend: xw
    APP_backend: excel
    ChatGPT_1:
      api_base: https://api.openai.com/v1
      api_keys:
      max_new_tokens: 256
      max_retries: 20
      max_total_tokens: 16384
      model_name: gpt-4o-mini
      prompt_format: gpt-chat-prompt
      sleep_time: 20
      temperature: 0.6
      timeout: 50
      topk: 0
    ChatGPT_2:
      api_base: https://api.openai.com/v1
      api_keys: []
      max_new_tokens: 256
      max_retries: 20
      sleep_time: 20
      temperature: 0.4
      timeout: 50
      topk: 0
    add_example_data2feedback: false
    api_doc_path: config/API_document.yaml
    max_cycle_times: 20
    max_error_count: 999
    prompt_path: config/prompt.yaml
    use_doc_in_syspromt: true
    use_ext_doc: true
    use_oracle_API_doc: false
    use_same_LLM: true
  path:
    gt_path: ../dataset/task_sheet_answers_v2
    save_path: ../output_dir/
    source_path: ../dataset/task_sheets/
    task_path: ../dataset/dataset_159_copy.xlsx
  repeat: 1
  worker: 1
finish_time: '2024-10-09 03:06:27'
start_time: '2024-10-09 02:03:44'
