path:
  source_path: ../dataset/task_sheets
  save_path: D:\SheetCopilot_data\action_diff_granularity\Chart1
  task_path: ../dataset/dataset.xlsx
  gt_path: ../dataset/task_sheet_answers_v2

repeat: 1