path:
  source_path: ../dataset/task_sheets/
  save_path: ../output_dir/
  task_path: ../dataset/dataset_113_copy.xlsx
  gt_path: ../dataset/task_sheet_answers_v2

worker: 1
repeat: 1

Agent:
  API_backend: "xw"
  APP_backend: "excel"
  prompt_path: config/prompt.yaml
  api_doc_path: config/API_document.yaml
  use_doc_in_syspromt: true
  use_ext_doc: true
  use_same_LLM: true
  use_oracle_API_doc: false
  add_example_data2feedback: false

  max_cycle_times: 30
  max_error_count: 999

  ChatGPT_1: # GPT-4o-mini
    # model_name: 'gpt-3.5-turbo-16k'
    model_name: "gpt-4o-mini"
    prompt_format: gpt-chat-prompt
    max_total_tokens: 16384
    max_new_tokens: 256
    topk: 0
    temperature: 0.5
    timeout: 50
    max_retries: 20
    sleep_time: 30
    api_base: https://api.openai.com/v1
    api_keys: []
  ChatGPT_2: # GPT-4o
    model_name: "gpt-4o"
    prompt_format: gpt-chat-prompt
    max_total_tokens: 16384
    max_new_tokens: 256
    topk: 0
    temperature: 0.5
    timeout: 50
    max_retries: 20
    sleep_time: 30
    api_base: https://api.openai.com/v1
    api_keys: []
  Llaama_3_3:
    model_name: "llama-3.3-70B"
    temperature: 0.5
    model: "llama-3.3-70b-versatile"
    timeout: 50
    max_retries: 20
    api_keys: []
  Gemma_2:
    model_name: "gemma2-9B"
    temperature: 0.5
    model: "gemma2-9b-it"
    timeout: 50
    max_retries: 20
    api_keys: []
  Mistral:
    model_name: "mistral-7B"
    temperature: 0.5
    model: "mixtral-8x7b-32768"
    timeout: 50
    max_retries: 20
    api_keys: []
