path:
  source_path: ../ActionTransformer/Excel_data/example_sheets_part1/task_sheets
  save_path: ../output_dataset_513_no_api_doc
  task_path: ../ActionTransformer/Excel_data/example_sheets_part1/SU_adaptation_sample/dataset.xlsx
  gt_path: ../ActionTransformer/Excel_data/example_sheets_part1/task_sheet_answers

worker: 2
repeat: 1

Agent:
  API_backend: 'xw'
  APP_backend: 'excel'
  prompt_path: config/prompt4.yaml
  api_doc_path: config/API_document.yaml
  ChatGPT_1:
    temperature: 0.0
    timeout: 50
    max_retries: 20
    sleep_time: 20
    api_base: https://api.openai.com/v1
    api_keys: [
      # 'sk-XWUkrLrPeUjqQ1k9ipAaHig4DgDyd2jhh09eVIVRwvhRTi5g',
      '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',
      # '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',
      # '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',
      # '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',
    ]
  ChatGPT_2:
    temperature: 0.0
    timeout: 50
    max_retries: 20
    sleep_time: 20
    api_base: https://api.openai.com/v1
    api_keys: [
      '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',
      # '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',
      # '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',
      # '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',
    ]