path:
  source_path: ../dataset/task_sheets
  save_path: ./results
  task_path: ../dataset/dataset.xlsx
  gt_path: ../dataset/task_sheet_answers

worker: 1
repeat: 1

Agent:
  API_backend: 'xw'
  APP_backend: 'excel'
  prompt_path: config/prompt.yaml
  api_doc_path: config/API_document.yaml
  use_doc_in_syspromt: false
  use_ext_doc: true
  use_same_LLM: false
  use_oracle_API_doc: false
  add_example_data2feedback: false

  max_cycle_times: 12
  max_error_count: 4

  ChatGPT_1:
    max_total_tokens: 16000
    max_new_tokens: 256
    topk: 0
    temperature: 0.0
    timeout: 50
    max_retries: 20
    sleep_time: 20
    api_base: https://api.openai.com/v1
    model_name: 'gpt-3.5-turbo-16k'
    prompt_format: gpt
    api_keys: [
      "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"
    ]
  ChatGPT_2:
    max_total_tokens: 16000
    max_new_tokens: 256
    topk: 0
    temperature: 0.0
    timeout: 50
    max_retries: 20
    sleep_time: 20
    api_base: https://api.openai.com/v1
    model_name: 'gpt-3.5-turbo-0613'
    prompt_format: gpt
    api_keys: [
      "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"
    ]