path:
  source_path: D:\Github\ActionTransformer\Excel_data\example_sheets_part1\task_sheets
  save_path: D:\SheetCopilot_data\Round1_T_0
  task_path: D:\Github\ActionTransformer\Excel_data\example_sheets_part1\SU_adaptation_sample\dataset.xlsx
  gt_path: D:\Github\ActionTransformer\Excel_data\example_sheets_part1\task_sheet_answers

worker: 2
repeat: 1

Agent:
  API_backend: 'xw'
  APP_backend: 'excel'
  prompt_path: config/prompt4.yaml
  api_doc_path: config/API_document.yaml
  use_ext_doc: true
  use_same_LLM: false
  use_oracle_API_doc: false
  max_cycle_times: 40
  max_queries: 30

  ChatGPT_1:
    max_total_tokens: 16000
    temperature: 0.6
    timeout: 50
    max_retries: 20
    sleep_time: 20
    api_base: https://api.openai.com/v1
    model_name: 'gpt-3.5-turbo-16k'
    prompt_format: gpt
    api_keys: [
      # 'sk-XWUkrLrPeUjqQ1k9ipAaHig4DgDyd2jhh09eVIVRwvhRTi5g',
      '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',
      # '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',
      # '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',
      # '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',
    ]
  ChatGPT_2:
    max_total_tokens: 16000
    temperature: 0.0
    timeout: 50
    max_retries: 20
    sleep_time: 20
    api_base: https://api.openai.com/v1
    model_name: 'gpt-3.5-turbo-0613'
    prompt_format: gpt
    api_keys: [
      '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',
      # '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',
      # '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',
      # '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',
    ]